import React from 'react'

export default function TermsCondition() {
    return (
        <>
        <div className="terms_policy m-5">
         <h3 className='color-orange my-4'><b>Terms & Conditions</b></h3>   
         <h6>GENERAL TERMS</h6>
         <p> 
3.1 The headings of each section in these Terms are only for the purpose of organizing the various provisions under these Terms in an orderly manner and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.<br/>
3.2 The use of this Platform by the Users is solely governed by these Terms as well as the Privacy Policy, and any modifications or amendments made thereto by the Company, from time to time, at its sole discretion. If you continue to access and use this Platform, you are agreeing to comply with and be bound by the following Terms and Conditions of Use and Our Privacy Policy. The User expressly agrees and acknowledges that these Terms and Policy are co-terminus in nature and that expiry/termination of either one will lead to the termination of the other.<br/>
3.3 The User unequivocally agrees that these Terms and the aforementioned Policy constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Platform, and that the same shall be deemed to be incorporated into these Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User and that the User's act of visiting any part of the Platform constitutes the User's full and final acceptance of these Terms and the aforementioned Policy.<br/>
3.4 The Company reserves the sole and exclusive right to amend or modify these Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. If the User does not adhere to the changes, they must stop using the Services at once. Their continuous use of the Services will signify your acceptance of the changed terms.<br/>
</p>
<h5>SERVICE OVERVIEW</h5>
<p> 
The platform, "Crejo.Fun" is an online e-learning platform which provides several extracurricular activities for children in the online format. The main aim of the services provided is the holistic development of the child. The content that the platform hosts is created exclusively for Company. Online classes may be conducted by professionals/ experts/ facilitators/ teachers contracted by the company or by teachers who may be employed or contracted by the Company for children aged from 4 (Four) to 16(Sixteen ) years of age. The classes will be conducted in private sessions (1: 1) or in small groups. In addition to this, the Company may also conduct summer camps or play shops for children from time to time in large groups of up to 500 children ( Five Hundred Children). Some of the content from the platform may be posted on social media which includes but not restricted to YouTube, Facebook, Instagram, etc and this may be viewed by larger number of Users.
</p>

<h3 className='color-orange my-3'><b>Privacy Policy</b></h3>
<p>We are sensitive to the scenario that we would be dealing with data and information of a personal nature. For purposes of this Privacy Policy “Personal Data” refers to information relating to an identified or identifiable individual, known as data subjects. Such information can be name, phone numbers, addresses, account details, online identifiers, photo, videos.
Data Subjects refers to existing users/customers including potential customers whose personal data is processed by availing the services offered by the Company. By using the website or the mobile application (hereinafter collectively referred to as the “Portal”) and providing your personal information, you consent to the terms of our online privacy policy and to our processing of such personal information for the purposes explained in this policy. By registering on the site or by subscribing to services and providing your contact details (email, mobile number, shipping address, credit card details, etc.), you agree that this action constitutes consent, for the purposes of telemarketing laws, to receive information about products and services from Createjoy Technologies Private Limited (hereinafter referred to as the “Company” or “Crejo”). This Privacy Policy is in compliance with the Global Data Protection Policy Regulations (hereinafter referred to as “GDPR Regulations”).
You hereby give free consent to the processing of your personal data for purposes of getting access to Portal. You confirm that this consent is freely given and is specific, informed, and is an unambiguous indication of your wishes to processing of your personal data for getting access to the Portal. Mandatory Personal data collected by the Company includes the email address of the child’s parent, date of birth of child, and mobile number of the parent for purposes of verification. The Company uses personal data for purposes of creating the Company’s content. This information is used by the Company for purposes of advising age-specific recommendations and is strictly not shared with any other party. Specific consent is obtained by the parent for children below 13 years of age.
Further, you hereby consent to our contacting you pursuant to the business relationship established using the information you provide to us. We request you to read the “Terms of Use” and to use it to help you make informed decisions. If you have any questions or concerns regarding this statement, you can email us at support@crejo.fun.
The Company ensures steady commitment to your usage on the Platform and privacy with regard to the protection of your invaluable information. This document contains information about the Website and mobile application https://www.crejo.fun/ (hereinafter referred to as the “Platform”).
In order to provide You with Our uninterrupted use of services, We may collect and, in some circumstances, disclose information about you with your permission. To ensure better protection of Your privacy, We provide this notice explaining Our information collection and disclosure policies, and the choices You make about the way Your information is collected and used.</p>
</div>
        </>
    )
}
